### ISSUE TITLE
Climate entitie fail to set up with HA 2021.12.10 and custom component

### ISSUE THREAD

**Issue by TobiasKneidl** [oischinger/ha_vicare#81] opened 2022-01-27 21:47 UTC
After the update to HA 2021.12.10 I also a error for the climate entitie set up with the custom component (master branch, latest commit). With the integrated component, the climate entitie works.

The other entities are working.

> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/vicare/climate.py", line 115, in async_setup_entry
    for circuit in hass.data[DOMAIN][config_entry.entry_id][VICARE_API].circuits:
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 59, in circuits
    return list([self.getCircuit(x) for x in self.getAvailableCircuits()])
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 45, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 331, in getAvailableCircuits
    return self.service.getProperty("heating.circuits")["properties"]["enabled"]["value"]
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 24, in getProperty
    data = self.__get_or_update_cache()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 36, in __get_or_update_cache
    data = self.fetch_all_features()
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 64, in fetch_all_features
    return self.oauth_manager.get(url)
  File "/usr/local/lib/python3.9/site-packages/PyViCare/PyViCareAbstractOAuthManager.py", line 37, in get
    response = self.__oauth.get(f"{API_BASE_URL}{url}").json()
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1290, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 219, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/vicare/climate.py, line 115: for circuit in hass.data[DOMAIN][config_entry.entry_id][VICARE_API].circuits:

**Comment by adorobis** [comment] 2022-01-27 21:51
Exactly the same issue for me. `pip list` shows required PyViCare version 2.16.1

**Comment by oischinger** [comment] 2022-01-28 07:33
Fixed with https://github.com/oischinger/ha_vicare/pull/82
Feedback would be appreciated since the issue wasn't reproducible for me

**Closed** 2022-01-28 07:33 UTC

**Comment by oischinger** [comment] 2022-01-28 07:34
Corresponding HA core PR is here: https://github.com/home-assistant/core/pull/65105

**Comment by TobiasKneidl** [comment] 2022-01-28 07:58
> Fixed with #82 Feedback would be appreciated since the issue wasn't reproducible for me

Is working again for me. Thank you very much for your great work and quick response!

**Comment by adorobis** [comment] 2022-01-28 16:36
Works ok for me as well now. Many thanks!
